// business_3_0/web/app/(app)/account/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { type HomeVariant, writeHomeVariant } from "@/lib/home-variant";
import { useHomeVariant } from "@/lib/use-home-variant";

const HOME_OPTIONS: { value: HomeVariant; label: string; desc: string }[] = [
  { value: "task", label: "方案 A：任务优先", desc: "突出下一步行动和今日任务" },
  { value: "metrics", label: "方案 B：数据概览", desc: "突出任务总览、关键数据和快捷操作" },
];

export default function AccountPage() {
  const router = useRouter();
  const homeVariant = useHomeVariant();

  const currentLabel =
    HOME_OPTIONS.find((o) => o.value === homeVariant)?.label.replace("方案 ", "") ?? "A：任务优先";

  function setVariant(v: HomeVariant) {
    writeHomeVariant(v);
    window.alert("首页方案已切换");
  }

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST", credentials: "include" });
    router.replace("/login");
    router.refresh();
  }

  return (
    <div className="px-3.5 pb-4 pt-4">
      <h1 className="mb-4 text-xl font-black text-[#111827]">我的</h1>
      <div className="overflow-hidden rounded-[14px] border border-[#e8edf4] bg-white shadow-[0_12px_28px_rgba(22,40,72,0.06)]">
      <div className="flex items-center gap-4 border-b border-[#edf1f5] p-4">
        <div className="flex h-[46px] w-[46px] shrink-0 items-center justify-center rounded-lg bg-[#176b87] text-sm font-extrabold text-white">
          B3
        </div>
        <div className="min-w-0">
          <p className="text-base font-extrabold text-[#182338]">Business 3.0 体验账号</p>
          <p className="mt-1 text-sm text-[#6b7485]">当前模式：{homeVariant === "task" ? "任务优先" : "数据概览"}</p>
        </div>
      </div>

      <div className="border-b border-[#edf1f5] p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p className="text-[15px] font-extrabold text-[#182338]">首页方案</p>
            <p className="mt-1 text-sm leading-relaxed text-[#6b7485]">用于测试不同首页对处理效率的影响</p>
          </div>
          <span className="shrink-0 rounded-full bg-[#eaf3ff] px-2.5 py-1 text-xs font-extrabold text-[#1478ff]">
            {currentLabel}
          </span>
        </div>
        <div className="mt-4 grid grid-cols-2 gap-2">
          {HOME_OPTIONS.map((opt) => (
            <button
              key={opt.value}
              type="button"
              onClick={() => setVariant(opt.value)}
              className={`min-h-[5.5rem] rounded-xl border px-3 py-3 text-left transition ${
                homeVariant === opt.value
                  ? "border-[#1478ff] bg-[#f4f9ff]"
                  : "border-[#dce3ea] bg-white active:bg-[#f8fafc]"
              }`}
            >
              <span
                className={`block text-sm font-extrabold leading-snug ${
                  homeVariant === opt.value ? "text-[#1478ff]" : "text-[#182338]"
                }`}
              >
                {opt.label}
              </span>
              <span className="mt-2 block text-xs leading-relaxed text-[#6b7485]">{opt.desc}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="divide-y divide-[#edf1f5]">
        <div className="flex min-h-[3.25rem] items-center justify-between px-4 text-sm font-bold text-[#182338]">
          <span>体验版本</span>
          <span className="font-extrabold text-[#176b87]">0.1.0</span>
        </div>
        <div className="flex min-h-[3.25rem] items-center justify-between px-4 text-sm font-bold text-[#182338]">
          <span>数据来源</span>
          <span className="font-extrabold text-[#176b87]">本地 Mock</span>
        </div>
        <button
          type="button"
          className="flex min-h-[3.25rem] w-full items-center justify-between px-4 text-left text-sm font-bold text-[#182338] active:bg-[#f8fafc]"
          onClick={() => window.alert("体验反馈（v0.1 未接独立路由）")}
        >
          <span>提交反馈</span>
          <span className="font-extrabold text-[#176b87]">进入 ›</span>
        </button>
      </div>

      <div className="p-4">
        <button
          type="button"
          className="w-full rounded-xl border border-[#dce5f0] py-3 text-sm font-extrabold text-[#1f2937] transition active:bg-[#f8fafc]"
          onClick={() => void logout()}
        >
          退出登录
        </button>
      </div>
      </div>
    </div>
  );
}

// business_3_0/pages/account/index.vue
<template>
  <view class="page">
    <view class="profile panel">
      <text class="avatar">B3</text>
      <view class="profile-copy">
        <text class="name">Business 3.0 体验账号</text>
        <text class="muted">当前模式：{{ mode }}</text>
      </view>
    </view>

    <view class="section panel home-switch">
      <view class="switch-head">
        <view>
          <text class="switch-title">首页方案</text>
          <text class="switch-copy">用于测试不同首页对处理效率的影响</text>
        </view>
        <text class="current-choice">{{ currentHomeLabel }}</text>
      </view>

      <view class="option-grid">
        <button
          v-for="option in homeOptions"
          :key="option.value"
          class="home-option"
          :class="{ active: homeVariant === option.value }"
          @tap="setHomeVariant(option.value)"
        >
          <text class="option-title">{{ option.label }}</text>
          <text class="option-copy">{{ option.desc }}</text>
        </button>
      </view>
    </view>

    <view class="section panel menu">
      <view class="menu-row">
        <text>体验版本</text>
        <text class="muted">0.1.0</text>
      </view>
      <view class="menu-row">
        <text>数据来源</text>
        <text class="muted">本地 Mock</text>
      </view>
      <view class="menu-row" @tap="openFeedback">
        <text>提交反馈</text>
        <text class="link">进入</text>
      </view>
    </view>
  </view>
</template>

<script>
import { getRuntimeMode } from '../../services/api/index.js';

export default {
  data() {
    return {
      mode: getRuntimeMode(),
      homeVariant: 'task',
      homeOptions: [
        { value: 'task', label: '方案 A：任务优先', desc: '突出下一步行动和今日任务' },
        { value: 'metrics', label: '方案 B：数据概览', desc: '突出任务总览、关键数据和快捷操作' }
      ]
    };
  },
  computed: {
    currentHomeLabel() {
      const current = this.homeOptions.find((item) => item.value === this.homeVariant);
      return current ? current.label.replace('方案 ', '') : 'A：任务优先';
    }
  },
  onShow() {
    this.homeVariant = uni.getStorageSync('business_3_home_variant') || 'task';
  },
  methods: {
    setHomeVariant(value) {
      this.homeVariant = value;
      uni.setStorageSync('business_3_home_variant', value);
      uni.showToast({ title: '首页方案已切换', icon: 'none' });
    },
    openFeedback() {
      uni.navigateTo({ url: '/pages/feedback/index' });
    }
  }
};
</script>

<style scoped>
.profile {
  display: flex;
  align-items: center;
  gap: 22rpx;
  padding: 26rpx 24rpx;
}

.avatar {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 92rpx;
  height: 92rpx;
  border-radius: 8rpx;
  background: #176b87;
  color: #ffffff;
  font-size: 30rpx;
  font-weight: 800;
}

.profile-copy {
  min-width: 0;
}

.name {
  display: block;
  color: #182338;
  font-size: 32rpx;
  font-weight: 800;
  line-height: 42rpx;
}

.profile-copy .muted {
  display: block;
  margin-top: 8rpx;
  font-size: 26rpx;
  line-height: 36rpx;
}

.menu {
  overflow: hidden;
}

.home-switch {
  padding: 24rpx;
}

.switch-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 20rpx;
}

.switch-title {
  display: block;
  color: #182338;
  font-size: 30rpx;
  font-weight: 800;
  line-height: 40rpx;
}

.switch-copy {
  display: block;
  margin-top: 8rpx;
  color: #6b7485;
  font-size: 26rpx;
  line-height: 36rpx;
}

.current-choice {
  flex: none;
  padding: 8rpx 12rpx;
  border-radius: 999rpx;
  background: #eaf3ff;
  color: #1478ff;
  font-size: 24rpx;
  font-weight: 800;
}

.option-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14rpx;
  margin-top: 22rpx;
}

.home-option {
  min-height: 144rpx;
  padding: 20rpx 18rpx;
  border: 1rpx solid #dce3ea;
  border-radius: 12rpx;
  background: #ffffff;
  text-align: left;
}

.home-option.active {
  border-color: #1478ff;
  background: #f4f9ff;
}

.option-title {
  display: block;
  color: #182338;
  font-size: 28rpx;
  font-weight: 800;
  line-height: 38rpx;
}

.home-option.active .option-title {
  color: #1478ff;
}

.option-copy {
  display: block;
  margin-top: 10rpx;
  color: #6b7485;
  font-size: 24rpx;
  line-height: 34rpx;
}

.menu-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  min-height: 104rpx;
  padding: 0 24rpx;
  border-bottom: 1rpx solid #edf1f5;
  color: #182338;
  font-size: 28rpx;
  font-weight: 700;
}

.menu-row:last-child {
  border-bottom: 0;
}

.link {
  color: #176b87;
  font-size: 28rpx;
  font-weight: 800;
}
</style>
