// business_3_0/pages/projects/index.vue
<template>
  <view class="page">
    <view class="project-list">
      <view v-for="project in projects" :key="project.id" class="project-card panel">
        <view class="project-head">
          <view>
            <text class="project-name">{{ project.name }}</text>
            <text class="project-stage">{{ project.stage }}</text>
          </view>
          <text class="owner">{{ project.owner }}</text>
        </view>

        <view class="progress">
          <view class="progress-line">
            <view class="progress-fill" :style="{ width: project.progress + '%' }"></view>
          </view>
          <text class="progress-text">{{ project.progress }}%</text>
        </view>

        <view class="risk-row">
          <text class="muted">当前关注</text>
          <text class="risk">{{ project.risk }}</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script>
import { api } from '../../services/api/index.js';

export default {
  data() {
    return {
      projects: []
    };
  },
  onLoad() {
    api.getProjects().then((projects) => {
      this.projects = projects;
    });
  }
};
</script>

<style scoped>
.project-list {
  display: flex;
  flex-direction: column;
  gap: 18rpx;
}

.project-card {
  padding: 24rpx;
}

.project-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 20rpx;
}

.project-name {
  display: block;
  color: #182338;
  font-size: 34rpx;
  font-weight: 800;
  line-height: 44rpx;
}

.project-stage {
  display: block;
  margin-top: 8rpx;
  color: #6b7485;
  font-size: 24rpx;
  line-height: 32rpx;
}

.owner {
  color: #176b87;
  font-size: 26rpx;
  font-weight: 800;
  line-height: 36rpx;
}

.progress {
  display: grid;
  grid-template-columns: 1fr 80rpx;
  align-items: center;
  gap: 18rpx;
  margin-top: 30rpx;
}

.progress-line {
  height: 14rpx;
  overflow: hidden;
  border-radius: 999rpx;
  background: #edf1f5;
}

.progress-fill {
  height: 100%;
  border-radius: 999rpx;
  background: #176b87;
}

.progress-text {
  color: #182338;
  font-size: 26rpx;
  font-weight: 800;
  text-align: right;
}

.risk-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20rpx;
  margin-top: 24rpx;
}

.risk-row .muted,
.risk {
  font-size: 24rpx;
  line-height: 34rpx;
}

.risk {
  color: #b7791f;
  font-weight: 700;
  text-align: right;
}
</style>

// business_3_0/web/app/(app)/projects/page.tsx
"use client";

import { useQuery } from "@tanstack/react-query";
import type { Project } from "@/lib/mock-data";
import { fetchJson } from "@/lib/fetch-json";

type ProjectsResponse = { items: Project[] };

export default function ProjectsPage() {
  const q = useQuery({
    queryKey: ["/api/projects"],
    queryFn: () => fetchJson<ProjectsResponse>("/api/projects"),
  });

  if (q.isPending) {
    return (
      <div className="space-y-3">
        <div className="h-8 w-32 animate-pulse rounded bg-[var(--xlink-panel-soft)]" />
        <div className="h-28 animate-pulse rounded-lg bg-[var(--xlink-panel-soft)]" />
      </div>
    );
  }
  if (q.isError) {
    return (
      <div className="panel p-6 text-center text-[var(--xlink-red)]">
        加载失败
        <button type="button" className="mt-4 block w-full text-[var(--xlink-primary)]" onClick={() => void q.refetch()}>
          重试
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <h1 className="text-lg font-bold text-[var(--xlink-text)]">项目</h1>
      <ul className="space-y-3">
        {q.data.items.map((p) => (
          <li key={p.id} className="panel p-4">
            <div className="flex items-start justify-between gap-2">
              <div>
                <p className="font-semibold text-[var(--xlink-text)]">{p.name}</p>
                <p className="mt-1 text-xs text-[var(--xlink-muted)]">{p.stage} · 负责人 {p.owner}</p>
              </div>
              <span className="text-sm font-bold text-[var(--xlink-primary)]">{p.progress}%</span>
            </div>
            <p className="mt-2 text-xs text-[var(--xlink-amber)]">{p.risk}</p>
            <div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--xlink-panel-soft)]">
              <div
                className="h-full rounded-full bg-[var(--xlink-primary)] transition-all"
                style={{ width: `${p.progress}%` }}
              />
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}
